version: "3"

services:
  app:
    build: .
    container_name: micro-videos-typescript-app
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    networks:
      - mynetwork
    extra_hosts:
      - host.docker.internal:host-gateway
      
  db:
    image: mysql:5.7
    container_name: micro-videos-typescript-db
    profiles:
      - dev
    restart: always
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    networks:
      - mynetwork
    ports:
      - 3306:3306
    extra_hosts:
      - host.docker.internal:host-gateway

  db_test:
    image: mysql:5.7
    container_name: micro-videos-typescript-db-test
    environment:
      - MYSQL_DATABASE=micro_videos_test
      - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
    networks:
      - mynetwork
    ports:
      - 3306:3306
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  mynetwork:
    driver: bridge
